version: "3.9"
services:
 mono:
  image: mono:latest
  container_name: mono_1
  ports:
   - "8080:8080"
  volumes:
   - D:\Shea\Documents\436\A2:/code
  stdin_open: true
  tty: true
 java:
  image: openjdk:latest
  container_name: java_1
  ports:
   - "8081:80"
  volumes:
   - D:\Shea\Documents\436\A2:/code
  stdin_open: true
  tty: true